/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.Closeable;

import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author leiz03
 */
public class AdiminGUI extends javax.swing.JFrame {

    /**
     * Creates new form AdiminGUI
     */
    public AdiminGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void close() {

		WindowEvent winClosingEvent = new WindowEvent(this,
				WindowEvent.WINDOW_CLOSING);
		Toolkit.getDefaultToolkit().getSystemEventQueue()
				.postEvent(winClosingEvent);

	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addBookButton = new javax.swing.JButton();
        manageBookButton = new javax.swing.JButton();
        addReceptionistButton = new javax.swing.JButton();
        manageReceptionistButton = new javax.swing.JButton();
        btnBookLendingReport = new javax.swing.JButton();
        btnBookPurchasedReport = new javax.swing.JButton();
        logoffButton = new javax.swing.JButton();
        btnFineRecord = new javax.swing.JButton();
        btnPopularBooksReport = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin Main Menu");

        addBookButton.setText("Purchase Books");
        addBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookButtonActionPerformed(evt);
            }
        });

        manageBookButton.setText("Manage Books");
        manageBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBookButtonActionPerformed(evt);
            }
        });

        addReceptionistButton.setText("Add Receptionist");
        addReceptionistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addReceptionistButtonActionPerformed(evt);
            }
        });

        manageReceptionistButton.setText("Manage Receptionist");
        manageReceptionistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageReceptionistButtonActionPerformed(evt);
            }
        });

        btnBookLendingReport.setText("Book Lending Report");
        btnBookLendingReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookLendingReportActionPerformed(evt);
            }
        });

        btnBookPurchasedReport.setText("Book Purchased Report");
        btnBookPurchasedReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookPurchasedReportActionPerformed(evt);
            }
        });

        logoffButton.setText("Logoff");
        logoffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoffButtonActionPerformed(evt);
            }
        });

        btnFineRecord.setText("Fine  Report");
        btnFineRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFineRecordActionPerformed(evt);
            }
        });

        btnPopularBooksReport.setText("Popular Books Report");
        btnPopularBooksReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPopularBooksReportActionPerformed(evt);
            }
        });

        jButton1.setText("Customer Time Spend Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBookLendingReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addReceptionistButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addBookButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBookPurchasedReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(manageBookButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageReceptionistButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFineRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPopularBooksReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(100, 100, 100)
                .addComponent(logoffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addBookButton, addReceptionistButton, btnBookLendingReport, btnBookPurchasedReport, btnFineRecord, btnPopularBooksReport, manageBookButton, manageReceptionistButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBookButton)
                    .addComponent(manageBookButton))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addReceptionistButton)
                    .addComponent(manageReceptionistButton))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBookLendingReport)
                    .addComponent(btnFineRecord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBookPurchasedReport)
                    .addComponent(btnPopularBooksReport))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(logoffButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButton1)))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBookButtonActionPerformed
        // TODO add your handling code here:
    	close();
    	BookGUI_ForAdmin gui = new BookGUI_ForAdmin();
    	gui.setVisible(true);
    }//GEN-LAST:event_manageBookButtonActionPerformed

    private void logoffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoffButtonActionPerformed
        // TODO add your handling code here:
    	// System.exit(0);
    	close();
    	LoginGUI gui = new LoginGUI();
    	gui.setVisible(true);
    }//GEN-LAST:event_logoffButtonActionPerformed

    private void btnFineRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFineRecordActionPerformed
        // TODO add your handling code here:        
        FineReport fineReport = new FineReport();
        fineReport.setVisible(true);
    }//GEN-LAST:event_btnFineRecordActionPerformed

    private void manageReceptionistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageReceptionistButtonActionPerformed
        // TODO add your handling code here:
        close();
    	ManageRecepitonist_ForAdmin gui = new ManageRecepitonist_ForAdmin();
    	gui.setVisible(true);
    }//GEN-LAST:event_manageReceptionistButtonActionPerformed

    private void btnBookLendingReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookLendingReportActionPerformed
        // TODO add your handling code here:
        BookLendingReport gui = new BookLendingReport();
    	gui.setVisible(true);
    }//GEN-LAST:event_btnBookLendingReportActionPerformed

    private void btnBookPurchasedReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookPurchasedReportActionPerformed
        // TODO add your handling code here:        
        Admin_purchaseReport gui = new Admin_purchaseReport();
        gui.frmPurchasedBooksReport.setVisible(true);
    }//GEN-LAST:event_btnBookPurchasedReportActionPerformed

    private void btnPopularBooksReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPopularBooksReportActionPerformed
        // TODO add your handling code here:        
        PopularBooksReport gui = new PopularBooksReport();
        gui.setVisible(true);
    }//GEN-LAST:event_btnPopularBooksReportActionPerformed

    private void addBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Admin_purchaseBook gui = new Admin_purchaseBook();
        gui.frmPurchaseABook.setVisible(true);
    }//GEN-LAST:event_addBookButtonActionPerformed

    private void addReceptionistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addReceptionistButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Admin_addReceptionist gui = new Admin_addReceptionist();
        gui.frmAddAReceptionist.setVisible(true);
    }//GEN-LAST:event_addReceptionistButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TimeSpendReport_ForAdmin timeSpendReport_ForAdmin =new TimeSpendReport_ForAdmin();
        timeSpendReport_ForAdmin.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdiminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdiminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdiminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdiminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdiminGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBookButton;
    private javax.swing.JButton addReceptionistButton;
    private javax.swing.JButton btnBookLendingReport;
    private javax.swing.JButton btnBookPurchasedReport;
    private javax.swing.JButton btnFineRecord;
    private javax.swing.JButton btnPopularBooksReport;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton logoffButton;
    private javax.swing.JButton manageBookButton;
    private javax.swing.JButton manageReceptionistButton;
    // End of variables declaration//GEN-END:variables

}
